version: '2'

services:
  node:
    image: node:8-alpine
    working_dir: /usr/src/app
    depends_on:
    - mongo
    ports:
    - "8080:8080"
    volumes:
    - "./app:/usr/src/app"
    environment:
    - NODE_ENV=development
    - MONGO_URI=mongodb://mongo:27017/test
    command: yarn run start

  mongo:
    image: mongo:3.4
